services:
  excalidraw:
    image: ghcr.io/magnifikus/excalipure:latest
    restart: unless-stopped
    volumes:
      - excalidraw-data:/app/data
    build:
      context: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.exp.rule=Host(`exp.yourdomain.com`)"
      - "traefik.http.routers.exp.tls=true"
      - "traefik.http.routers.exp.tls.certresolver=yourresolver"
      - "traefik.http.services.exp.loadbalancer.server.port=80"
      - "traefik.http.routers.exp.entrypoints=websecure"
    networks:
      - proxy

volumes:
  excalidraw-data:

networks:
  proxy:
   external: true
